description    = ""
name           = "terraform-github-repository"
private        = "false"
has_wiki       = "true"
has_downloads  = "true"
has_issues     = "true"
team_permission= "push"
team_name      = "cds"